Helpdesk/Controllers/UserProfileController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.OpenIdConnect;

namespace Helpdesk.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {
        private readonly ClaimsHelper _claimsHelper;
        public UserProfileController(ClaimsHelper claimsHelper)
        {
            _claimsHelper = claimsHelper;
        }

        public async Task<ActionResult> Index()
        {
            try
            {
                var helper = _claimsHelper;
                var groupNames = await helper.GetGroupNames();
                ViewBag.groups = string.Join(",", groupNames);
                var user = helper.GetUser();

                return View(user);
            }
            catch (AdalException)
            {
                return View("Error");
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;

                return View("Relogin");
            }
        }

        public void RefreshSession()
        {
            HttpContext.GetOwinContext().Authentication.Challenge(
                new AuthenticationProperties { RedirectUri = "/UserProfile" },
                OpenIdConnectAuthenticationDefaults.AuthenticationType);
        }
    }
}

Helpdesk/Views/UserProfile/Index.cshtml
@using Microsoft.Azure.ActiveDirectory.GraphClient
@model IUser

@{
    ViewBag.Title = "User Profile";
}
<h2>@ViewBag.Title.</h2>

<table class="table table-bordered table-striped">
    

    <tr>
        <td>Display Name</td>
        <td>@Model.DisplayName</td>
    </tr>
    <tr>
        <td>First Name</td>
        <td>@Model.GivenName</td>
    </tr>
    <tr>
        <td>Last Name</td>
        <td>@Model.Surname</td>
    </tr>
    <tr>
        <td>My Azure AD Groups</td>
        <td>
            @ViewBag.groups
        </td>

    </tr>
</table>

Helpdesk/Views/UserProfile/Relogin.cshtml
@using Microsoft.Azure.ActiveDirectory.GraphClient

@{
    ViewBag.Title = "User Profile";
}
<h2>@ViewBag.Title.</h2>
error: @ViewBag.Error;
<p>
    The token for accessing the Graph API has expired.
    Click @Html.ActionLink("here", "RefreshSession", "UserProfile", null, null) to sign-in and get a new access token.
</p>